#if WINDOWS

using System.Runtime.InteropServices;

namespace Altim.Platform.Windows.Interop;

/// <summary>
/// The Win32 surface Altim uses on Windows: one message-only window, one hidden
/// top-level window, the shell notification area, GDI+ for decoding the icon assets,
/// and the tool-help snapshot used to detect provider processes.
/// </summary>
/// <remarks>
/// <para>
/// Every entry point is generated by <c>LibraryImport</c> rather than <c>DllImport</c>
/// so the marshalling stubs are source generated and the assembly stays Native AOT
/// clean, and every module is resolved from <c>System32</c> so a DLL of the same name
/// beside the executable cannot be loaded instead.
/// </para>
/// <para>
/// Nothing here reads a process command line. The tool-help snapshot exposes an
/// executable name, a process id and a parent id and nothing else, which is the whole
/// reason it is used in preference to a WMI query.
/// </para>
/// </remarks>
internal static unsafe partial class NativeMethods
{
    /// <summary>Base of the private message range a window may use for itself.</summary>
    internal const uint WM_APP = 0x8000;

    /// <summary>Base of the message range the shell uses for notification icon events.</summary>
    internal const uint WM_USER = 0x0400;

    internal const uint WM_DESTROY = 0x0002;
    internal const uint WM_CLOSE = 0x0010;
    internal const uint WM_NULL = 0x0000;
    internal const uint WM_LBUTTONUP = 0x0202;
    internal const uint WM_RBUTTONUP = 0x0205;
    internal const uint WM_CONTEXTMENU = 0x007B;
    internal const uint WM_POWERBROADCAST = 0x0218;

    /// <summary>Version 4 primary activation: mouse or keyboard.</summary>
    internal const uint NIN_SELECT = WM_USER + 0;

    /// <summary>Version 4 primary activation from the keyboard.</summary>
    internal const uint NIN_KEYSELECT = WM_USER + 1;

    internal const uint NIM_ADD = 0x00000000;
    internal const uint NIM_MODIFY = 0x00000001;
    internal const uint NIM_DELETE = 0x00000002;
    internal const uint NIM_SETVERSION = 0x00000004;

    internal const uint NIF_MESSAGE = 0x00000001;
    internal const uint NIF_ICON = 0x00000002;
    internal const uint NIF_TIP = 0x00000004;
    internal const uint NIF_SHOWTIP = 0x00000080;

    /// <summary>
    /// Click messages carry screen coordinates and the icon id, and the shell shows the
    /// standard tooltip. Anything lower loses the coordinates.
    /// </summary>
    internal const uint NOTIFYICON_VERSION_4 = 4;

    internal const int S_OK = 0;

    internal const uint WS_POPUP = 0x80000000;
    internal const uint WS_EX_TOOLWINDOW = 0x00000080;
    internal const uint WS_EX_NOACTIVATE = 0x08000000;

    /// <summary>Parent handle that makes a window message-only.</summary>
    internal static readonly IntPtr HWND_MESSAGE = -3;

    internal const int GWLP_USERDATA = -21;

    internal const int SM_CXSMICON = 49;

    /// <summary>Walks to the root window of a hierarchy.</summary>
    internal const uint GA_ROOT = 2;

    internal const uint IMAGE_ICON = 1;
    internal const uint LR_LOADFROMFILE = 0x00000010;
    internal const uint LR_DEFAULTCOLOR = 0x00000000;

    /// <summary>Resource id of the stock application icon.</summary>
    internal static readonly IntPtr IDI_APPLICATION = 32512;

    internal const uint MF_STRING = 0x00000000;
    internal const uint MF_SEPARATOR = 0x00000800;
    internal const uint MF_GRAYED = 0x00000001;
    internal const uint MF_CHECKED = 0x00000008;

    internal const uint TPM_LEFTALIGN = 0x0000;
    internal const uint TPM_RIGHTBUTTON = 0x0002;
    internal const uint TPM_BOTTOMALIGN = 0x0020;
    internal const uint TPM_NONOTIFY = 0x0080;
    internal const uint TPM_RETURNCMD = 0x0100;

    internal const uint DEVICE_NOTIFY_WINDOW_HANDLE = 0x00000000;

    /// <summary>Power broadcast subtype carrying a registered power setting value.</summary>
    internal const int PBT_POWERSETTINGCHANGE = 0x8013;

    /// <summary>Power broadcast subtype for an automatic resume, including a wake timer.</summary>
    internal const int PBT_APMRESUMEAUTOMATIC = 0x0012;

    /// <summary>Power broadcast subtype for a resume where the user is present.</summary>
    internal const int PBT_APMRESUMESUSPEND = 0x0007;

    /// <summary>
    /// Console display state. On a modern standby machine this is the transition that
    /// actually marks a wake; the classic APM resume broadcasts can be absent.
    /// </summary>
    internal static readonly Guid GUID_CONSOLE_DISPLAY_STATE =
        new(0x6fe69556, 0x704a, 0x47a0, 0x8f, 0x24, 0xc2, 0x8d, 0x93, 0x6f, 0xda, 0x47);

    internal const uint TH32CS_SNAPPROCESS = 0x00000002;
    internal const uint PROCESS_QUERY_LIMITED_INFORMATION = 0x00001000;
    internal static readonly IntPtr INVALID_HANDLE_VALUE = -1;

    [LibraryImport("kernel32.dll", SetLastError = true)]
    internal static partial IntPtr GetModuleHandleW(char* lpModuleName);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial ushort RegisterClassExW(WNDCLASSEXW* lpwcx);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool UnregisterClassW(char* lpClassName, IntPtr hInstance);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr CreateWindowExW(
        uint dwExStyle,
        char* lpClassName,
        char* lpWindowName,
        uint dwStyle,
        int x,
        int y,
        int nWidth,
        int nHeight,
        IntPtr hWndParent,
        IntPtr hMenu,
        IntPtr hInstance,
        IntPtr lpParam);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyWindow(IntPtr hWnd);

    [LibraryImport("user32.dll")]
    internal static partial IntPtr DefWindowProcW(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

    [LibraryImport("user32.dll")]
    internal static partial int GetMessageW(MSG* lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool TranslateMessage(MSG* lpMsg);

    [LibraryImport("user32.dll")]
    internal static partial IntPtr DispatchMessageW(MSG* lpMsg);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool PostMessageW(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

    [LibraryImport("user32.dll")]
    internal static partial void PostQuitMessage(int nExitCode);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial uint RegisterWindowMessageW(char* lpString);

    [LibraryImport("user32.dll", EntryPoint = "SetWindowLongPtrW", SetLastError = true)]
    private static partial IntPtr SetWindowLongPtr64(IntPtr hWnd, int nIndex, IntPtr dwNewLong);

    [LibraryImport("user32.dll", EntryPoint = "SetWindowLongW", SetLastError = true)]
    private static partial int SetWindowLong32(IntPtr hWnd, int nIndex, int dwNewLong);

    [LibraryImport("user32.dll", EntryPoint = "GetWindowLongPtrW", SetLastError = true)]
    private static partial IntPtr GetWindowLongPtr64(IntPtr hWnd, int nIndex);

    [LibraryImport("user32.dll", EntryPoint = "GetWindowLongW", SetLastError = true)]
    private static partial int GetWindowLong32(IntPtr hWnd, int nIndex);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetCursorPos(POINT* lpPoint);

    [LibraryImport("user32.dll")]
    internal static partial int GetSystemMetricsForDpi(int nIndex, uint dpi);

    [LibraryImport("user32.dll")]
    internal static partial uint GetDpiForWindow(IntPtr hWnd);

    [LibraryImport("user32.dll")]
    internal static partial uint GetDpiForSystem();

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr FindWindowW(char* lpClassName, char* lpWindowName);

    [LibraryImport("user32.dll")]
    internal static partial IntPtr WindowFromPoint(POINT point);

    [LibraryImport("user32.dll")]
    internal static partial IntPtr GetAncestor(IntPtr hWnd, uint gaFlags);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial int GetClassNameW(IntPtr hWnd, char* lpClassName, int nMaxCount);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr LoadImageW(IntPtr hInst, char* name, uint type, int cx, int cy, uint fuLoad);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr LoadIconW(IntPtr hInstance, IntPtr lpIconName);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyIcon(IntPtr hIcon);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr CreatePopupMenu();

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool AppendMenuW(IntPtr hMenu, uint uFlags, UIntPtr uIDNewItem, char* lpNewItem);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool DestroyMenu(IntPtr hMenu);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial int TrackPopupMenuEx(IntPtr hMenu, uint uFlags, int x, int y, IntPtr hwnd, IntPtr lptpm);

    [LibraryImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool SetForegroundWindow(IntPtr hWnd);

    [LibraryImport("user32.dll", SetLastError = true)]
    internal static partial IntPtr RegisterPowerSettingNotification(IntPtr hRecipient, Guid* powerSettingGuid, uint flags);

    [LibraryImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool UnregisterPowerSettingNotification(IntPtr handle);

    [LibraryImport("shell32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool Shell_NotifyIconW(uint dwMessage, NOTIFYICONDATAW* lpData);

    [LibraryImport("shell32.dll")]
    internal static partial int Shell_NotifyIconGetRect(NOTIFYICONIDENTIFIER* identifier, RECT* iconLocation);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    internal static partial IntPtr CreateToolhelp32Snapshot(uint dwFlags, uint th32ProcessID);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool Process32FirstW(IntPtr hSnapshot, PROCESSENTRY32W* lppe);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool Process32NextW(IntPtr hSnapshot, PROCESSENTRY32W* lppe);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool CloseHandle(IntPtr hObject);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    internal static partial IntPtr OpenProcess(uint dwDesiredAccess, [MarshalAs(UnmanagedType.Bool)] bool bInheritHandle, uint dwProcessId);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static partial bool GetProcessTimes(IntPtr hProcess, long* creation, long* exit, long* kernel, long* user);

    [LibraryImport("gdiplus.dll")]
    internal static partial int GdiplusStartup(nuint* token, GdiplusStartupInput* input, IntPtr output);

    [LibraryImport("gdiplus.dll")]
    internal static partial void GdiplusShutdown(nuint token);

    [LibraryImport("gdiplus.dll")]
    internal static partial int GdipCreateBitmapFromFile(char* filename, IntPtr* bitmap);

    [LibraryImport("gdiplus.dll")]
    internal static partial int GdipCreateHICONFromBitmap(IntPtr bitmap, IntPtr* hicon);

    [LibraryImport("gdiplus.dll")]
    internal static partial int GdipDisposeImage(IntPtr image);

    /// <summary>
    /// Stores a pointer in a window's user data slot. 32-bit Windows has no
    /// <c>SetWindowLongPtrW</c> export, so the width is chosen at run time.
    /// </summary>
    /// <param name="hWnd">The window.</param>
    /// <param name="index">The slot, for example <see cref="GWLP_USERDATA"/>.</param>
    /// <param name="value">The value to store.</param>
    internal static void SetWindowPointer(IntPtr hWnd, int index, IntPtr value)
    {
        if (IntPtr.Size == 8)
        {
            _ = SetWindowLongPtr64(hWnd, index, value);
        }
        else
        {
            _ = SetWindowLong32(hWnd, index, (int)value);
        }
    }

    /// <summary>Reads a pointer from a window's user data slot.</summary>
    /// <param name="hWnd">The window.</param>
    /// <param name="index">The slot, for example <see cref="GWLP_USERDATA"/>.</param>
    /// <returns>The stored value, or zero when nothing has been stored.</returns>
    internal static IntPtr GetWindowPointer(IntPtr hWnd, int index) =>
        IntPtr.Size == 8 ? GetWindowLongPtr64(hWnd, index) : GetWindowLong32(hWnd, index);

    /// <summary>Sign-extends the low word of a packed coordinate pair.</summary>
    /// <param name="value">The packed value.</param>
    /// <returns>The x coordinate, which is negative on a monitor left of the primary.</returns>
    internal static int LowInt16(IntPtr value) => (short)(value.ToInt64() & 0xFFFF);

    /// <summary>Sign-extends the high word of a packed coordinate pair.</summary>
    /// <param name="value">The packed value.</param>
    /// <returns>The y coordinate, which is negative on a monitor above the primary.</returns>
    internal static int HighInt16(IntPtr value) => (short)((value.ToInt64() >> 16) & 0xFFFF);
}

/// <summary>A window class registration.</summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct WNDCLASSEXW
{
    /// <summary>Size of this structure in bytes.</summary>
    public uint cbSize;

    /// <summary>Class style flags.</summary>
    public uint style;

    /// <summary>Pointer to the window procedure.</summary>
    public IntPtr lpfnWndProc;

    /// <summary>Extra bytes to allocate following the class structure.</summary>
    public int cbClsExtra;

    /// <summary>Extra bytes to allocate following the window instance.</summary>
    public int cbWndExtra;

    /// <summary>Module that owns the class.</summary>
    public IntPtr hInstance;

    /// <summary>Class icon.</summary>
    public IntPtr hIcon;

    /// <summary>Class cursor.</summary>
    public IntPtr hCursor;

    /// <summary>Class background brush.</summary>
    public IntPtr hbrBackground;

    /// <summary>Resource name of the class menu.</summary>
    public char* lpszMenuName;

    /// <summary>Class name.</summary>
    public char* lpszClassName;

    /// <summary>Small class icon.</summary>
    public IntPtr hIconSm;
}

/// <summary>A thread message.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct MSG
{
    /// <summary>Target window, or zero for a thread message.</summary>
    public IntPtr hwnd;

    /// <summary>Message identifier.</summary>
    public uint message;

    /// <summary>First message parameter.</summary>
    public IntPtr wParam;

    /// <summary>Second message parameter.</summary>
    public IntPtr lParam;

    /// <summary>Time the message was posted.</summary>
    public uint time;

    /// <summary>Cursor position at the time the message was posted.</summary>
    public POINT pt;
}

/// <summary>A point in physical screen pixels.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct POINT
{
    /// <summary>Horizontal coordinate.</summary>
    public int x;

    /// <summary>Vertical coordinate.</summary>
    public int y;
}

/// <summary>A rectangle in physical screen pixels, with exclusive right and bottom edges.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RECT
{
    /// <summary>Left edge.</summary>
    public int left;

    /// <summary>Top edge.</summary>
    public int top;

    /// <summary>Right edge, exclusive.</summary>
    public int right;

    /// <summary>Bottom edge, exclusive.</summary>
    public int bottom;
}

/// <summary>
/// The notification area icon. The string buffers are declared as 16-bit integers
/// rather than <c>char</c> so the structure is unambiguously blittable and can be
/// passed by pointer with no marshalling stub at all.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NOTIFYICONDATAW
{
    /// <summary>Size of this structure in bytes.</summary>
    public uint cbSize;

    /// <summary>Window that receives the callback messages.</summary>
    public IntPtr hWnd;

    /// <summary>Icon identifier, unique within the owning window.</summary>
    public uint uID;

    /// <summary>Which of the remaining members are valid.</summary>
    public uint uFlags;

    /// <summary>Message the shell posts to <see cref="hWnd"/> for this icon.</summary>
    public uint uCallbackMessage;

    /// <summary>The icon to display.</summary>
    public IntPtr hIcon;

    /// <summary>Tooltip text, null terminated.</summary>
    public fixed ushort szTip[128];

    /// <summary>Icon state.</summary>
    public uint dwState;

    /// <summary>Which state bits are valid.</summary>
    public uint dwStateMask;

    /// <summary>Balloon body, unused by Altim.</summary>
    public fixed ushort szInfo[256];

    /// <summary>Balloon timeout, or the notify icon version for <c>NIM_SETVERSION</c>.</summary>
    public uint uVersion;

    /// <summary>Balloon title, unused by Altim.</summary>
    public fixed ushort szInfoTitle[64];

    /// <summary>Balloon flags, unused by Altim.</summary>
    public uint dwInfoFlags;

    /// <summary>Alternative icon identity, unused by Altim.</summary>
    public Guid guidItem;

    /// <summary>Balloon icon, unused by Altim.</summary>
    public IntPtr hBalloonIcon;
}

/// <summary>Identifies one notification area icon for a geometry query.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct NOTIFYICONIDENTIFIER
{
    /// <summary>Size of this structure in bytes.</summary>
    public uint cbSize;

    /// <summary>Window that owns the icon.</summary>
    public IntPtr hWnd;

    /// <summary>Icon identifier.</summary>
    public uint uID;

    /// <summary>Alternative icon identity, unused by Altim.</summary>
    public Guid guidItem;
}

/// <summary>Payload of a <c>PBT_POWERSETTINGCHANGE</c> broadcast.</summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct POWERBROADCAST_SETTING
{
    /// <summary>The setting that changed.</summary>
    public Guid PowerSetting;

    /// <summary>Length of <see cref="Data"/> in bytes.</summary>
    public uint DataLength;

    /// <summary>First byte of the value.</summary>
    public fixed byte Data[4];
}

/// <summary>GDI+ initialisation input. Only the version field is set.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct GdiplusStartupInput
{
    /// <summary>GDI+ version, always 1.</summary>
    public uint GdiplusVersion;

    /// <summary>Debug callback, unused.</summary>
    public IntPtr DebugEventCallback;

    /// <summary>Non-zero to suppress the GDI+ background thread.</summary>
    public int SuppressBackgroundThread;

    /// <summary>Non-zero to suppress external image codecs.</summary>
    public int SuppressExternalCodecs;
}

/// <summary>
/// One row of a tool-help process snapshot. The snapshot carries an executable name
/// and identifiers only; there is no field here that could hold a command line.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PROCESSENTRY32W
{
    /// <summary>Size of this structure in bytes.</summary>
    public uint dwSize;

    /// <summary>Unused.</summary>
    public uint cntUsage;

    /// <summary>Process identifier.</summary>
    public uint th32ProcessID;

    /// <summary>Unused.</summary>
    public UIntPtr th32DefaultHeapID;

    /// <summary>Unused.</summary>
    public uint th32ModuleID;

    /// <summary>Thread count.</summary>
    public uint cntThreads;

    /// <summary>Parent process identifier.</summary>
    public uint th32ParentProcessID;

    /// <summary>Base priority.</summary>
    public int pcPriClassBase;

    /// <summary>Unused.</summary>
    public uint dwFlags;

    /// <summary>Executable file name, with no directory component.</summary>
    public fixed ushort szExeFile[260];
}

#endif
